---
apiVersion: v1
kind: Pod
metadata:
  name: roadsterpod
spec:
  containers:
    - name: roadster
      image: techsriman/roadster:1.0
      ports:
        - name: roadsterhttp
          containerPort: 8080
          protocol: TCP
      readinessProbe:
        httpGet:
          path: /roadster/actuator/health/readiness
          port: 8080
        initialDelaySeconds: 5
        timeoutSeconds: 10
        failureThreshold: 3
      livenessProbe:
        httpGet:
          path: /roadster/actuator/health/liveness
          port: 8080
        initialDelaySeconds: 15
        timeoutSeconds: 10
        failureThreshold: 3
      resources:
        requests:
          cpu: "500m"
          memory: "500M"
        limits:
          cpu: "1000m"  
          memory: "1024M"
