apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: hangoutrs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hangout
      version: "1.0"
  template:
    metadata:
      labels:
        app: hangout
        version: "1.0"    
    spec:
      containers:
        - name: hangout
          image: techsriman/hangout:1.0
          ports:
            - name: tomcat
              containerPort: 8080
              protocol: TCP    