apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysqlpv
spec:
  storageClassName: mysqlstorageclass
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /Users/sriman/data    
...