apiVersion: v1
kind: Pod
metadata: 
  name: mysqlpod
spec:
  containers:
    - name: mysql
      image: mysql:8.3.0
      ports:
        - name: mysqlport
          containerPort: 3306
          protocol: TCP
      volumeMounts:
        - name:  mysqlvolume
          mountPath:  /var/lib/mysql   
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name:  mysqlsecret
  volumes:
    - name: mysqlvolume
      persistentVolumeClaim:
        claimName: mysqlpvc