Vagrant.configure(2) do | config |
    config.vm.box = "ubuntu/jammy64"
    config.vm.network "public_network", ip: "192.168.0.19"

    config.vm.provider "virtualbox" do | vb |
        vb.cpus=4
        vb.memory=4096
        vb.name="egprovisioner"
        vb.gui=false
    end
    #config.vm.provision "installJdk", type: "shell", inline: "sudo apt update -y && sudo apt install -y openjdk-17-jdk"
    #config.vm.provision "shell", inline: "sudo apt update -y && sudo apt install -y net-tools"
    # config.vm.provision "installJdk", type: "shell" do | prov |
    #     prov.inline = "sudo apt update -y && sudo apt install -y net-tools"
    # end
    config.vm.provision "installJdkThroughExternal", type: "shell" do | prov |
        prov.path = "installJdk17.sh"
    end
end