Vagrant.configure(2) do | config |
    config.vm.box = "ubuntu/jammy64"
    config.vm.network "public_network", ip: "192.168.0.10", bridge: ["Killer Wireless-n/a/ac 1535 Wireless Network Adapter"]
end