FROM ubuntu:24.04
ARG RELEASE_NM
ARG RELEASE_VERSION

RUN echo "RELEASE_NM: ${RELEASE_NM} and RELEASE_VERSION: ${RELEASE_VERSION}}" > ~/args
ENV RELEASE_NM=${RELEASE_NM}
ENV RELEASE_VERSION=${RELEASE_VERSION}

CMD [ "/bin/bash", "-c", "echo RELEASE_NM: ${RELEASE_NM} and RELEASE_VERSION: ${RELEASE_VERSION}" ]


