---
apiVersion: v1
kind: Pod
metadata:
  name: apache2pod
  labels:
    appName: apache2
    version: "1.0"
  annotations:
    description: apache2 http server to host an static application
    license: GNU Public License
spec:
  containers:
    - name: apache2
      image: ubuntu/apache2:latest
      ports:
        - name: http
          containerPort: 80
          protocol: TCP
      resources:
        requests:
          cpu: "250m"     
          memory: "250M"
        limits:
          cpu: "500m"  
          memory: "500M"

...