---
apiVersion: v1
kind: Pod
metadata:
  name: roadster
  labels:
    appName: roadster
    version: "1.0"
    environment: stage
spec:
  containers:
    - name: roadster
      image: techsriman/roadster:1.0
      ports:
        - name: http
          containerPort: 8080
          protocol: TCP
...