Vagrant.configure(2) do | config |
    # global configurations, and are applied for all the providers

    config.vm.box ="ubuntu/jammy64"
    config.vm.network "public_network", ip: "192.168.0.12"

    config.vm.provider "virtualbox" do | virtualbox |
        virtualbox.cpus=4
        virtualbox.memory=2048
        virtualbox.gui=true
        virtualbox.name="dbserver"
        virtualbox.customize ["modifyvm", :id, "--vram", "256"]
    end
end