apiVersion: v1
kind: Service
metadata:
  name: {{ include "hangout.fullname" . }}
  labels:
    {{- include "hangout.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: tomcatport
      protocol: TCP
      name: http
  selector:
    {{- include "hangout.selectorLabels" . | nindent 4 }}
