apiVersion: batch/v1
kind: Job
metadata:
  name: logcleanupjob
spec:
  template:
    metadata:
      name: logcleanup
    spec:
      containers:
        - name: logcleaner
          image:  logcleaner:1.0
          command:
            - "bin/bash"
            - "-c"
            - "/tmp/loop.sh"
      restartPolicy: OnFailure  